export const DEFAULT_PROCESS_AREA = {
  key_set: [
    "KEY SET SUB podmontaż",
    "KEY SET montaż",
    "D/LOCK montaż",
    "KEY SET test",
    "LOCK BODY montaż",
    "LOCK BODY test",
    "LS/LP maszyna",
    "LS/LP stanowisko kontrolne",
    "MIRROR CD montaż",
    "MIRROR CD test",
    "PW REAR/ASSIST CD montaż",
    "PW REAR/ASSSIT CD test",
    "PW MAIN CD montaż",
    "PW MAIN CD test",
  ],
  "c_pad/0fd": [
    "Mirror podmontaż",
    "Mirror montaż",
    "Mirror test",
    "PW rear/assist montaż",
    "PW rear/assist test",
    "PW Main montaż",
    "PW Main test",
    "Facia/Hazard montaż",
    "Facia/Hazard test",
    "Paddle montaż",
    "Paddle test",
    "EPB montaż",
    "EPB test",
    "IMS montaż",
    "IMS test",
    "Console CD montaż",
    "Console CD test",
    "Console SBC montaż",
    "Console SBC test",
  ],
  multifunction: [
    "MF SUB podmontaż",
    "MF FINAL montaż",
    "MF FINAL test",
    "MF LEVER lutowanie 1",
    "MF LEVER lutowanie 2",
    "MF LEVER montaż & test",
    "MIRROR podmontaż",
    "MIRROR montaż",
    "MIRROR test",
    "PW REAR/ASSIST PDE montaż",
    "PW REAR/ASSSIT PDE test",
    "PW MAIN PDE montaż",
    "PW MAIN PDE test",
    "FACIA/HAZARD PDE/NQ5 montaż",
    "FACIA/HAZARD  PDE/NQ5 test",
    "EPB CD montaż",
    "EPB CD test",
    "IMS CD & CONSOLE CD/ PDE montaż",
    "IMS CD & CONSOLE CD/ PDE  test",
    "ARMREST NX4 montaż",
    "ARMREST NX4 test",
    "REMOCON PDE montaż",
    "REMOCON PDE test",
  ],
  remocon: [
    "CPAD ZGRZEWANIE HLLD",
    "CPAD CD/PDE montaż",
    "CPAD CD/PDE test",
    "CPAD NQ5 montaż",
    "CPAD NQ5 test",
    "CPAD NX4 montaż",
    "CPAD NX4 test",
    "PADDLE montaż",
    "PADDLE test",
    "CONSOLE DRIVE MODE NQ5 montaż",
    "CONSOLE DRIVE MODE NQ5 test",
    "S/WARMER  NQ5 montaż",
    "S/WARMER  NQ5 test",
    "KEYBOARD montaż",
    "KEYBOARD test",
  ],
  "pw/console": [
    "SEAT WARMER SBW/SBC NQ5 & CD montaż",
    "SEAT WARMER SBW/SBC NQ5 & CD test",
    "CONSOLE MT NQ5 & MT NX4 montaż",
    "CONSOLE MT NQ5 & MT NX4 test",
    "CONSOLE SBW NX4 montaż",
    "CONSOLE SBW NX4 test",
    "CONSOLE SBC montaż",
    "CONSOLE SBC test",
    "EPB NX4 montaż",
    "EPB NX4 test",
    "FACIA CD montaż",
    "FACIA CD test",
    "REMOCON NQ5 montaż",
    "REMOCON NQ5 test",
    "REMOCON CD montaż",
    "REMOCON CD test",
    "PAB montaż",
    "PAB test",
    "LDC montaż",
    "LDC test",
  ],
  renault: [
    "KEY RING ASSY parowanie/ fobowanie kluczy",
    "SUB  ROTOR podmontaż",
    "FUEL LOCK",
    "DOOR LOCK BBG",
    "DOOR LOCK XDD",
    "DOOR LOCK XJI/XJF",
    "LOCK HOUSING ASSY XJI/XJF",
    "MSCL  XJI/XJF & BBG & XDD",
    "DOOR LOCK XJK/X62",
    "LOCK HOUSING ASSY XJK/X62",
    "MSCL XJK/X62",
  ],
  smt: [
    "SMT Vacuum Loader",
    "SMT Laser Marking Machine",
    "SMT Scanning Conveyor",
    "SMT Screen Printer",
    "SMT Solder Paste Inspector",
    "SMT Chip Mounter",
    "SMT Reflow",
    "SMT Automatic Optical Inspection",
    "SELECTIVE SOLDERING Automatic Screw Fastener",
    "SELECTIVE SOLDERING Selective Soldering",
    "SELECTIVE SOLDERING BSI",
    "COATING Machine",
    "ROUTER Machine",
    "WAVE Automatic Flux  Spray  System",
    "WAVE Automatic Solder WAVE",
    "EOL",
    "EOL Auto camera",
  ],
};
